"""add motivo to historico_status

Revision ID: 00feff76f2e8
Revises: 538dcc87e22b
Create Date: 2026-05-27 00:05:48.183265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00feff76f2e8'
down_revision = '538dcc87e22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_status', schema=None) as batch_op:
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
