"""Add categoria_id to Usuario

Revision ID: 5035267b7a75
Revises: e728badb6240
Create Date: 2026-04-28 16:57:35.972386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5035267b7a75'
down_revision = 'e728badb6240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_usuarios_categoria_id_categorias'), 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuarios_categoria_id_categorias'), type_='foreignkey')
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
