"""add user area

Revision ID: 538dcc87e22b
Revises: 5d9956ef6eb1
Create Date: 2026-05-26 23:18:23.645581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538dcc87e22b'
down_revision = '5d9956ef6eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
