"""initial schema

Revision ID: 5d9956ef6eb1
Revises: 
Create Date: 2026-05-26 20:04:49.188311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9956ef6eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prioridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANALISE', 'EM_ATENDIMENTO', 'ATRIBUIR_TECNICO', 'MUDAR_CATEGORIA', 'MUDAR_PRIORIDADE', 'AGUARDANDO_CLIENTE', 'AGUARDANDO_TECNICO', 'AGUARDANDO_PECA', 'ATENDIMENTO_AGENDADO', 'RESOLVIDO', 'FECHADO', 'CANCELADO', name='statusenum'), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['prioridades.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_status')
    op.drop_table('comentarios')
    op.drop_table('chamados')
    op.drop_table('usuarios')
    op.drop_table('prioridades')
    op.drop_table('categorias')
    op.drop_table('cargos')
    # ### end Alembic commands ###
