"""empty message

Revision ID: e728badb6240
Revises: 
Create Date: 2026-04-28 15:40:47.774478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e728badb6240'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias')),
    sa.UniqueConstraint('nome', name=op.f('uq_categorias_nome'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('chamados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('status_atual', sa.String(length=50), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('solicitante_id', sa.UUID(), nullable=False),
    sa.Column('atendente_id', sa.UUID(), nullable=True),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['usuarios.id'], name=op.f('fk_chamados_atendente_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('fk_chamados_categoria_id_categorias'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], name=op.f('fk_chamados_solicitante_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chamados'))
    )
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamados_atendente_id'), ['atendente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_chamados_prioridade', ['prioridade'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_solicitante_id'), ['solicitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_status_atual'), ['status_atual'], unique=False)

    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chamado_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('fk_comentarios_autor_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], name=op.f('fk_comentarios_chamado_id_chamados'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comentarios'))
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentarios_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_chamado_id'), ['chamado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_criado_em'), ['criado_em'], unique=False)

    op.create_table('historico_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chamado_id', sa.UUID(), nullable=False),
    sa.Column('alterado_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=False),
    sa.Column('status_novo', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alterado_por_usuario_id'], ['usuarios.id'], name=op.f('fk_historico_status_alterado_por_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], name=op.f('fk_historico_status_chamado_id_chamados'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico_status'))
    )
    with op.batch_alter_table('historico_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_status_alterado_em'), ['alterado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_status_chamado_id'), ['chamado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_status_chamado_id'))
        batch_op.drop_index(batch_op.f('ix_historico_status_alterado_em'))

    op.drop_table('historico_status')
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentarios_criado_em'))
        batch_op.drop_index(batch_op.f('ix_comentarios_chamado_id'))
        batch_op.drop_index(batch_op.f('ix_comentarios_autor_id'))

    op.drop_table('comentarios')
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamados_status_atual'))
        batch_op.drop_index(batch_op.f('ix_chamados_solicitante_id'))
        batch_op.drop_index('ix_chamados_prioridade')
        batch_op.drop_index(batch_op.f('ix_chamados_criado_em'))
        batch_op.drop_index(batch_op.f('ix_chamados_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_chamados_atendente_id'))

    op.drop_table('chamados')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
